version: '3'
services:
  recoil-app:
    container_name: recoil-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - '3000:3000'
